# Generated by Django 5.0.7 on 2024-07-31 14:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_alter_book_author'),
    ]

    operations = [
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Видавництва',
            },
        ),
        migrations.CreateModel(
            name='PublisherCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('published_date', models.DateField()),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.book')),
                ('publisher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.publisher')),
            ],
            options={
                'verbose_name_plural': 'Книги Видавництв',
            },
        ),
        migrations.DeleteModel(
            name='Publication',
        ),
        migrations.AddField(
            model_name='publisher',
            name='books',
            field=models.ManyToManyField(through='pages.PublisherCompany', to='pages.book'),
        ),
    ]
