# Generated by Django 5.0.7 on 2024-08-09 12:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_publisher_publishercompany_delete_publication_and_more'),
    ]

    operations = [

        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.author'),
        ),
        migrations.AddConstraint(
            model_name='book',
            constraint=models.UniqueConstraint(fields=('publication_date',), name='unique_publication_date'),
        ),
    ]
