# Generated by Django 5.0.7 on 2024-08-01 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_publisher_publishercompany_delete_publication_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('created_date', models.DateField()),
            ],
            options={
                'verbose_name_plural': 'Категорії',
            },
        ),
        migrations.AddConstraint(
            model_name='book',
            constraint=models.UniqueConstraint(fields=('publication_date',), name='unique_publication_date'),
        ),
        migrations.AddConstraint(
            model_name='category',
            constraint=models.UniqueConstraint(fields=('name', 'created_date'), name='unique_category_name_per_month'),
        ),
    ]
