# Generated by Django 5.0.7 on 2024-08-01 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_category_book_unique_publication_date_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Категорії'},
        ),
        migrations.RemoveConstraint(
            model_name='category',
            name='unique_category_name_per_month',
        ),
        migrations.AddConstraint(
            model_name='category',
            constraint=models.UniqueConstraint(fields=('name', 'created_date'), name='unique_category_name_per_month'),
        ),
    ]
